AWSTemplateFormatVersion: 2010-09-09
Description: Creates all the INBOUND AND OUTBOUND IN THE VPC
Resources:
 SGBase:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: CREATE RULES POR INBOUND AND OUTBOUND
    VpcId: !ImportValue VPCID-proyecto
    GroupName: SGPROYECTO
    Tags:
      - Key: Name
        Value: SECURITY
    SecurityGroupIngress:
    - IpProtocol: -1
      CidrIp: 0.0.0.0/0
    
    SecurityGroupEgress:
    - IpProtocol: -1
      CidrIp: 0.0.0.0/0
      
Outputs:
   SGID:
    Description: ID OF THE SECURITY GROUP
    Value: !Ref SGBase
    Export:
      Name: "SG-PROYECTO"
   